e1:
	jupyter nbconvert --to notebook --execute p3_01.ipynb --output output.ipynb
e2:
	jupyter nbconvert --to notebook --execute p3_02.ipynb --output output.ipynb
e3:
	jupyter nbconvert --to notebook --execute p3_03.ipynb --output output.ipynb
e4:
	jupyter nbconvert --to notebook --execute p3_04.ipynb --output output.ipynb
